// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Dans Prisma v7, les URLs de connexion sont configurées ICI (et non dans schema.prisma)
// DATABASE_URL      → connexion principale pour l'app et les migrations
// SHADOW_DATABASE_URL → base "shadow" temporaire utilisée par `prisma migrate dev`
//                       pour calculer le diff entre l'état actuel et le schéma cible.

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
